
name: build-num
author: ebekker
description: Exposes an increasing build number to the containing workflow.

inputs:
  gist_token:
    description: The OAuth Token to use for reading/writing state in GIST.
    required: true
  version_key:
    description: An optional id to scope the build numbers.
    required: false

outputs:
  this_build_num:
    description: The global build number for the current repo.
  vers_build_num:
    description: The scoped build number for the argument version key.

runs:
  using: node12
  main: dist/index.js

branding:
  color: green
  icon: hash
