name: CI

on:
  push:
  release:
    types: published

jobs:

  _1_dotnet-build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-16.04

    steps:
      - name: dump gihub env
        env:
          GHCTX: ${{ toJson(github) }}
        run: echo "$GHCTX"

      - name: checkout
        uses: actions/checkout@v1

      - name: extract tag info
        id: extractTagInfo
        shell: pwsh
        run: |
          if ($env:GITHUB_REF -match '^refs/tags/v=(.+)') {
            $tagVersion = $Matches[1]
            if ($tagVersion -match '(.+)(-.+)') {
              $tagVersionPrefix = $Matches[1]
              $tagVersionSuffix = $Matches[2]
            }
            else {
              $tagVersionPrefix = $tagVersion
              $tagVersionSuffix = ''
            }
            ## Export as ENV VARS for subsequent steps
            Write-Host "Found matching Tag Version info:"
            Write-Host "::set-env name=TAG_VERSION::$tagVersion"
            Write-Host "::set-env name=TAG_VERSION_PREFIX::$tagVersionPrefix"
            Write-Host "::set-env name=TAG_VERSION_SUFFIX::$tagVersionSuffix"

            Write-Host "::set-output name=tag_version::$tagVersion"
            Write-Host "::set-output name=tag_version_prefix::$tagVersionPrefix"
            Write-Host "::set-output name=tag_version_suffix::$tagVersionSuffix"
          }
          else {
            ## Export as ENV VARS for subsequent steps
            Write-Host "NO MATCHING Tag Version info found, DEFAULTING:"
            Write-Host "::set-env name=TAG_VERSION::0-ci"
            Write-Host "::set-env name=TAG_VERSION_PREFIX::0"
            Write-Host "::set-env name=TAG_VERSION_SUFFIX::-ci"

            Write-Host "::set-output name=tag_version::$tagVersion"
            Write-Host "::set-output name=tag_version_prefix::0"
            Write-Host "::set-output name=tag_version_suffix::-ci"
          }

      # - name: build number (pwsh)
      #   shell: pwsh
      #   run: |
      #     ./.github/workflows/build-num.ps1               `
      #       -InformationAction Continue                   `
      #       -GitHubToken "${{ secrets.BUILD_NUM_OAUTH }}" `
      #       -VersionKey "$($env:TAG_VERSION_PREFIX)"

      #     Write-Host "Computing Build Version Suffix as:  "
      #     $buildVersionSuffix = ".$($env:VERS_BUILD_NUM)$($env:TAG_VERSION_SUFFIX)"
      #     Write-Host "::set-env name=BUILD_VERSION_SUFFIX::$($buildVersionSuffix)"

      - name: dump extract outputs
        shell: pwsh
        env:
          STEPS_CONTEXT:  ${{ toJson(steps) }}
        run: |
          Write-Host "Dumping job outputs:"
          Write-Host $env:STEPS_CONTEXT
          
      - name: build number (pwsh)
        uses: ./.github/actions/build-num
        with:
          gist_token: ${{ secrets.BUILD_NUM_OAUTH }}
          version_key: ${{ steps.extractTagInfo.output.tag_version_prefix }}

      - name: compute build version
        shell: pwsh
        run: |
          Write-Host "Computing Build Version Suffix as:  "
          $buildVersionSuffix = ".$($env:VERS_BUILD_NUM)$($env:TAG_VERSION_SUFFIX)"
          Write-Host "::set-env name=BUILD_VERSION_SUFFIX::$($buildVersionSuffix)"


      - name: build
        run:  dotnet build /p:VersionBuildNumber=$BUILD_VERSION_SUFFIX

      - name: package
        run:  dotnet pack /p:VersionBuildNumber=$BUILD_VERSION_SUFFIX
      
      - name: upload package as artifact
        if: startsWith(github.ref, 'refs/tags/v=')
        uses: actions/upload-artifact@v1
        with:
          name: package
          path: src/Bkkr.GitHub.TestActionsAndRegistry/bin/Debug


  _2_push-github-nuget:
    needs: _1_dotnet-build
    if: (github.event_name == 'push') && startsWith(github.ref, 'refs/tags/v=')

    #runs-on: ubuntu-latest
    runs-on: ubuntu-16.04

    steps:
      - name: dump gihub env
        env:
          GHCTX: ${{ toJson(github) }}
        run: echo "$GHCTX"

      - name: download package from artifact
        uses: actions/download-artifact@v1
        with:
          name: package

      - name: install nuget
        ## Win only:
        #uses: warrenbuckley/Setup-Nuget@v1
        uses: olegtarasov/download-nuget@v1

      - name: register nuget repo
        ## As per:
        ##  https://help.github.com/en/articles/configuring-nuget-for-use-with-github-package-registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #run:  nuget sources Add -Name "GPR" \
        run: |
          mono $NUGET_EXE sources Add -Name "GPR" \
            -Source "https://nuget.pkg.github.com/ebekker/index.json" \
            -UserName ebekker -Password $GITHUB_TOKEN
          find . -name *.nupkg
          mono $NUGET_EXE setapikey $GITHUB_TOKEN -Source "GPR"

      - name: publish
        run:  mono $NUGET_EXE push package/Bkkr.GitHub.TestActionsAndRegistry*.nupkg -Source GPR 
        #run:  dotnet nuget push Bkkr.GitHub.TestActionsAndRegistry.nupkg --source GPR 

  _3_push-public-nuget:
    needs: _1_dotnet-build
    if: (github.event_name == 'release') && startsWith(github.ref, 'refs/tags/v=')

    #runs-on: ubuntu-latest
    runs-on: ubuntu-16.04

    steps:
      - name: dump gihub env
        env:
          GHCTX: ${{ toJson(github) }}
        run: echo "$GHCTX"

      - name: download package from artifact
        uses: actions/download-artifact@v1
        with:
          name: package

      - name: PLACEHOLDER
        shell: pwsh
        run: |
          Write-Host "This is where I push to public NUGET.ORG"

      # - name: install nuget
      #   ## Win only:
      #   #uses: warrenbuckley/Setup-Nuget@v1
      #   uses: olegtarasov/download-nuget@v1

      # - name: register nuget repo
      #   ## As per:
      #   ##  https://help.github.com/en/articles/configuring-nuget-for-use-with-github-package-registry
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   #run:  nuget sources Add -Name "GPR" \
      #   run: |
      #     mono $NUGET_EXE sources Add -Name "GPR" \
      #       -Source "https://nuget.pkg.github.com/ebekker/index.json" \
      #       -UserName ebekker -Password $GITHUB_TOKEN
      #     find . -name *.nupkg
      #     mono $NUGET_EXE setapikey $GITHUB_TOKEN -Source "GPR"

      # - name: publish
      #   run:  mono $NUGET_EXE push package/Bkkr.GitHub.TestActionsAndRegistry*.nupkg -Source GPR 
      #   #run:  dotnet nuget push Bkkr.GitHub.TestActionsAndRegistry.nupkg --source GPR 
