name: CI

on: [push]

jobs:
  default-build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-16.04

    steps:
      - name: checkout
        uses: actions/checkout@v1

      #- name: Setup .NET Core
      #  uses: actions/setup-dotnet@v1
      #  with:
      #    dotnet-version: 2.2.108

      #- name: Build with dotnet
      #  run: dotnet build --configuration Release

      - name: build
        run:  dotnet build

      - name: package
        run:  dotnet pack

      - name: publish
        run:  nuget nuget push Bkkr.GitHub.TestActionsAndRegistry.nupkg --source GPR 
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
