on:
  issue_comment:
    types: [created, edited]

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: invoke action
        uses: ./.github/actions/invoke-pwsh
