
on: [push, create]

jobs:
  default-build:
    runs-on: ubuntu-16.04

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: dump env
        run: |
          echo "GITHUB_SHA        = $GITHUB_SHA"
          echo "GITHUB_REF        = $GITHUB_REF"
          echo "GITHUB_WORKFLOW   = $GITHUB_WORKFLOW"
          echo "GITHUB_ACTION     = $GITHUB_ACTION"
          echo "GITHUB_ACTOR      = $GITHUB_ACTOR"
          echo "GITHUB_EVENT_NAME = $GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH = $GITHUB_EVENT_PATH"
          echo "GITHUB_WORKSPACE  = $GITHUB_WORKSPACE"

      - name: dump event payload
        run: cat $GITHUB_EVENT_PATH

      - name: compute build numbers (pwsh)
        env:
          #BUILD_NUM_OAUTH: ${{ secrets.BUILD_NUM_OAUTH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        run: |
          pwsh -f ./.github/workflows/build-num.ps1  \
            -InformationAction Continue              \
            -GitHubToken ${{ secrets.BUILD_NUM_OAUTH }} \
            -VersionKey 0.0.0 
          echo "Dumping build numbers within step:"
          echo "GITHUB_WORKFLOW = $GITHUB_WORKFLOW"
          echo "THIS_BUILD_NUM = $THIS_BUILD_NUM"
          echo "VERS_BUILD_NUM = $VERS_BUILD_NUM"

      - name: dump build numbers
        run: |
          echo "THIS_BUILD_NUM = $THIS_BUILD_NUM"
          echo "VERS_BUILD_NUM = $VERS_BUILD_NUM"
