
name: Release

on: release

jobs:

  default-release:

    #runs-on: ubuntu-latest
    runs-on: ubuntu-16.04

    steps:
      - name: dump gihub env
        env:
          GHCTX: ${{ toJson(github) }}
        run: echo "$GHCTX"

      - name: extract tag info
        shell: pwsh
        run: |
          if ($env:GITHUB_REF -match '^refs/tags/v=(.+)') {
            $tagVersion = $Matches[1]
            if ($tagVersion -match '(.+)(-.+)') {
              $tagVersionPrefix = $Matches[1]
              $tagVersionSuffix = $Matches[2]
            }
            else {
              $tagVersionPrefix = $tagVersion
              $tagVersionSuffix = ''
            }
            ## Export as ENV VARS for subsequent steps
            Write-Host "Found matching Tag Version info:"
            Write-Host "::set-env name=TAG_VERSION::$tagVersion"
            Write-Host "::set-env name=TAG_VERSION_PREFIX::$tagVersionPrefix"
            Write-Host "::set-env name=TAG_VERSION_SUFFIX::$tagVersionSuffix"
          }
